name: butler_labs
description: A Pure Dart SDK for Butler Labs OCR
version: 0.0.1
homepage: https://codeontherocks.dev/

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.0

flutter: